version: '3.3'
services:
  datawhores:
    container_name: ofscraper
    image: datawhores/of-scraper:main
    user: "${UID:-1000}:${GID:-1000}"
    #we have to docker exec
    entrypoint: ["/bin/bash"]
    volumes:
    #change the host mountpoint
      - /home/john/.config/ofscraper:/root/.config/ofscraper
    command: ["-c","sleep infinity"]
    stdin_open: true # docker run -i
    tty: true        # docker run -t

#docker exec ofscraper ofscraper 

      

      